#is the location, 1 specific farm
@url = tfgrid.farm.1
threebot_id** = (S)
iyo_organization** = (S) # for backward compatibility
name** = (S)
wallet_addresses = (LS)
location = (O) !tfgrid.location.1
email = (email)
resource_prices = (LO) !tfgrid.node.resource.price.1

@url = tfgrid.node.resource.price.1
currency = "EUR,USD,TFT,AED,GBP" (E)
cru = (F)
mru = (F)
hru = (F)
sru = (F)
nru = (F)
