[book]
authors = ["3bot"]
language = "en"
multilingual = false
src = "."
title = "threefold.wiki"

[output.html.fold]
enable = true
level = 0

[output.html]
default-theme = "light"

[build]
build-dir = "/sandbox/var/mdbooks/threefold.wiki"
