@url = tfgrid.solutions.payment.1
rid = ""
explorer = ""
currency = ""
escrow_address = ""
escrow_asset = ""
total_amount = ""
transaction_fees = ""
payment_source = "" # wallet name or "3bot app"
farmers_payment = (dict)
